### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by marcochiesi** [ItalyCookieChoices/italy-cookie-choices-php-class#2]
Hi,
thanks for the creation of this class, it was useful to implement the cookie law banner and cookie block on a very old php site. I am a user of your WP plugin, and I appreciate the ability to use (almost) the same solution for old non-WP sites.
I found a few issues in it, so I made a pull request (#1) with fixes and improvements.

**Comment by overclokk** [comment]
Hi, @marcochiesi thank you too for your contribution, I just merged your pull :-)
